package com.myi.enums;

public enum ConfigProperties {
    URL,
    BROWSER,
    RUNMODE,
    OVERRIDEREPORTS,
    PASSEDSTEPSCREENSHOTS,
    FAILEDSTEPSCREENSHOTS,
    SKIPPEDSTEPSCREENSHOTS,
    RETRYFAILEDTESTS,
    SENDRESULTSTOELK
}
